#!/usr/bin/env bun
/** Build a completely offline, single-file ttyd --index artifact. */
const root = import.meta.dir;
const paths = {
  template: `${root}/src/template.html`,
  styles: `${root}/src/styles.css`,
  app: `${root}/src/app.tsx`,
  output: `${root}/index.html`,
};

/* Fetch exact production UMD releases only at build time. They are concatenated
   into the artifact; index.html itself performs no runtime network requests.
   No package.json or local node_modules are needed. */
const vendorUrls = [
  'https://unpkg.com/react@18.3.1/umd/react.production.min.js',
  'https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js',
  'https://cdn.jsdelivr.net/npm/@xterm/xterm@5.5.0/lib/xterm.js',
  'https://cdn.jsdelivr.net/npm/@xterm/addon-fit@0.10.0/lib/addon-fit.js',
  'https://cdn.jsdelivr.net/npm/@xterm/addon-web-links@0.11.0/lib/addon-web-links.js',
];
const xtermCssUrl = 'https://cdn.jsdelivr.net/npm/@xterm/xterm@5.5.0/css/xterm.css';
const fetchText = async (url) => {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Could not fetch ${url}: ${response.status}`);
  return response.text();
};
/* TypeScript catches invalid state/ref/layout/modal contracts before Bun's
   transpiler strips the types. Keep this separate: transpilation alone is not
   type checking. */
const typecheck = Bun.spawnSync(['tsc', '--noEmit', '-p', `${root}/tsconfig.json`], { stdout:'inherit', stderr:'inherit' });
if (typecheck.exitCode !== 0) throw new Error('TypeScript typecheck failed');

const [template, styles, source, xtermCss, ...vendor] = await Promise.all([
  Bun.file(paths.template).text(),
  Bun.file(paths.styles).text(),
  Bun.file(paths.app).text(),
  fetchText(xtermCssUrl),
  ...vendorUrls.map(fetchText),
]);

/* Bun compiles TSX. Authored modules import React normally; at bundle time
   these virtual modules bind those imports to the pinned UMD globals that are
   concatenated before the application bundle. */
const browserSource = source;
const reactGlobals = {
  name: 'react-umd-globals',
  setup(build) {
    build.onResolve({ filter: /^react$/ }, () => ({ path: 'react', namespace: 'umd' }));
    build.onResolve({ filter: /^react-dom\/client$/ }, () => ({ path: 'react-dom/client', namespace: 'umd' }));
    build.onLoad({ filter: /.*/, namespace: 'umd' }, ({ path }) => ({
      loader: 'js',
      contents: path === 'react'
        ? `const R=globalThis.React;export default R;export const {useCallback,useEffect,useId,useLayoutEffect,useMemo,useRef,useState}=R;`
        : `export const createRoot=globalThis.ReactDOM.createRoot;`,
    }));
  },
};
/* Keep the temporary entry beside canonical sources so relative imports such
   as ./commands.js resolve normally through Bun's module graph. */
const temp = `${root}/src/.ttydterm-build-${process.pid}-${Date.now()}.tsx`;
await Bun.write(temp, browserSource);
let bundle;
try {
  const result = await Bun.build({
    entrypoints: [temp],
    target: 'browser',
    format: 'iife',
    minify: true,
    jsx: { runtime: 'classic', factory: 'React.createElement', fragment: 'React.Fragment' },
    define: { 'process.env.NODE_ENV': '"production"' },
    plugins: [reactGlobals],
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Application bundle failed');
  }
  if (result.outputs.length !== 1) throw new Error(`Expected one JS output; found ${result.outputs.length}`);
  bundle = await result.outputs[0].text();
} finally {
  await Bun.file(temp).delete().catch(() => {});
}
const app = `${vendor.join('\n')}\n${bundle}`;

const slots = [
  ['/*__TTYDTERM_STYLES__*/', `${xtermCss.trimEnd()}\n${styles.trimEnd()}`],
  ['/*__TTYDTERM_APP__*/', app.trimEnd()],
];
let output = template;
for (const [sentinel, content] of slots) {
  const count = output.split(sentinel).length - 1;
  if (count !== 1) throw new Error(`Expected exactly one ${sentinel}; found ${count}`);
  /* Function replacement is essential: minified vendor code contains `$&`,
     which String.replace would otherwise expand back to the sentinel and
     corrupt JavaScript regex/string literals. */
  output = output.replace(sentinel, () => content);
}
const marker = '<!-- GENERATED by `bun run build.mjs` from src/. Offline: all runtime code is inline. Do not edit index.html directly. -->';
if (!output.startsWith('<!doctype html>')) throw new Error('Template must begin with <!doctype html>');
output = output.replace('<!doctype html>', `<!doctype html>\n${marker}`);
if (!output.endsWith('\n')) output += '\n';
await Bun.write(paths.output, output);
console.log(`built offline index.html (${new TextEncoder().encode(output).length} bytes)`);
